### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by graphiclunarkid** [DemocracyClub/candidate_questions#15]
So that I can learn more about this website
As a Candidate
I want to read a page of explanatory information

**Scenario: A candidate visits the about page**
Given I want more info about the site
When I visit the about page
Then I can read explanatory information

**Comment by EdwardBetts** [comment]
Mike suggested this text for the home page:

Ask your candidate #ge2015                                                                                                          

This is a prototype of a Q&A app for organisations to ask questions of people standing for office                                     

It uses [PopIt](http://popit.poplus.org/) in the back end, and should interoperate with other poplus components                        

Built by 89up Labs with help from: Open Rights Group + DemocracyClub
